### ISSUE TITLE
coordinates are rarely used by homo sapiens on planet earth to determine brightness of screens. homo sapiens on planet earth want to manually enter times when the brightness should go lower and when higher

### ISSUE THREAD

**Issue by stjema** [jacob-pro/solar-screen-brightness#23]
literally nobody wants their brightness to go down to 10% once its dark outside, because people dont leave the pc automatically just because its dark outside. 

right now in germany, where homo sapiens live, its dark outside at 20:00. do you think the homo sapiens wants a brightness value of 10% at 20:00?

**Comment by jacob-pro** [comment]
well then don't set it to 10% you moron

**Comment by jacob-pro** [comment]
on a more serious note the intention is that you match your screen brightness to the light level in your room.

In the daytime you probably have natural / sunlight coming in, whereas at nighttime you are going to have some sort of artificial light, depending on sunlight vs light bulb, you probably want different screen brightness.

If that doesn't suit you then please go away

**Comment by stjema** [comment]
sure its rational to reduce brightness a bit when sun is gone, i never said it isnt, but homo sapiens should also reduce brightness to the lowest value they can work with 1 hour before they go to bed to accelerate the time homo sapiens need to fall asleep.

if brightness is at 10% for one hour before homo sapiens goes to bed, it will help the average homo sapiens a lot falling asleep 1000 times faster. apology if alien did something wrong writing to human named jacob.

**Comment by jacob-pro** [comment]
well if you want to set brightness at a fixed time of day (regardless of season) you can already do this on Windows with another tool called ClickMonitorDDC

https://www.addictivetips.com/windows-tips/change-screen-brightness-time-of-day-on-windows-10/

if you care about going to sleep, then it is probably better to change the colour tone of your display (rather than brightness) which is already built into windows (Night light) or using f.lux 

![image](https://user-images.githubusercontent.com/16433349/192320660-f64289d0-2676-4321-a9fb-c73e6fd07923.png)

This tool is called "solar-screen-brightness" because it specifically varies your brightness with sunset times, if that is not for you, there are plenty of other tools out there which work differently

**Comment by stjema** [comment]
thanks ^^
btw flux alone without very dark screen doesnt work. they tested it with macos and their blue-remover app. didnt help at all. probably cause brightness was not 10% etc..
